export const GET_NR_OF_PENDING = "GET_NR_OF_PENDING";
export const GET_NR_OF_PENDING_SUCCESS = "GET_NR_OF_PENDING_SUCCESS";
export const GET_NR_OF_PENDING_FAIL = "GET_NR_OF_PENDING_FAIL";

export const GET_ANALYSIS_PENDING = "GET_ANALYSIS_PENDING";
export const GET_ANALYSIS_PENDING_SUCCESS = "GET_ANALYSIS_PENDING_SUCCESS";
export const GET_ANALYSIS_PENDING_FAIL = "GET_ANALYSIS_PENDING_FAIL";

export const SUBMIT_ANALYSIS_PENDING = "SUBMIT_ANALYSIS_PENDING";
export const SUBMIT_ANALYSIS_PENDING_SUCCESS = "SUBMIT_ANALYSIS_PENDING_SUCCESS";
export const SUBMIT_ANALYSIS_PENDING_FAIL = "SUBMIT_ANALYSIS_PENDING_FAIL";