export const ADD_TWITTER_AUTH = 'ADD_TWITTER_AUTH';
export const ADD_TWITTER_AUTH_SUCCESS = 'ADD_TWITTER_AUTH_SUCCESS';
export const ADD_TWITTER_AUTH_FAIL = 'ADD_TWITTER_AUTH_FAIL';

export const GET_TWITTER_AUTH_EXISTS = 'GET_TWITTER_AUTH_EXISTS';
export const GET_TWITTER_AUTH_EXISTS_SUCCESS = 'GET_TWITTER_AUTH_EXISTS_SUCCESS';
export const GET_TWITTER_AUTH_EXISTS_FAIL = 'GET_TWITTER_AUTH_EXISTS_FAIL';

export const GET_TWITTER_AUTH_ERROR = 'GET_TWITTER_AUTH_ERROR';
export const GET_TWITTER_AUTH_ERROR_SUCCESS = 'GET_TWITTER_AUTH_ERROR_SUCCESS';
export const GET_TWITTER_AUTH_ERROR_FAIL = 'GET_TWITTER_AUTH_ERROR_FAIL';