export const GET_NR_OF_ANALYSIS = "GET_NR_OF_ANALYSIS";
export const GET_NR_OF_ANALYSIS_SUCCESS = "GET_NR_OF_ANALYSIS_SUCCESS";
export const GET_NR_OF_ANALYSIS_FAIL = "GET_NR_OF_ANALYSIS_FAIL";

export const GET_ANALYSIS = "GET_ANALYSIS";
export const GET_ANALYSIS_SUCCESS = "GET_ANALYSIS_SUCCESS";
export const GET_ANALYSIS_FAIL = "GET_ANALYSIS_FAIL";

export const GET_SINGLE_ANALYSIS = "GET_SINGLE_ANALYSIS";
export const GET_SINGLE_ANALYSIS_SUCCESS = "GET_SINGLE_ANALYSIS_SUCCESS";
export const GET_SINGLE_ANALYSIS_FAIL = "GET_SINGLE_ANALYSIS_FAIL";


export const CHANGE_PAGE = 'CHANGE_PAGE';
export const CHANGE_SIZE = 'CHANGE_SIZE';
export const CHANGE_SORT = 'CHANGE_SORT';
export const CHANGE_ORDER = 'CHANGE_ORDER';


export const ADD_TWITTER_AUTH = 'ADD_TWITTER_AUTH';
export const ADD_TWITTER_AUTH_SUCCESS = 'ADD_TWITTER_AUTH_SUCCESS';
export const ADD_TWITTER_AUTH_FAIL = 'ADD_TWITTER_AUTH_FAIL';

export const GET_TWITTER_AUTH_EXISTS = 'GET_TWITTER_AUTH_EXISTS';
export const GET_TWITTER_AUTH_EXISTS_SUCCESS = 'GET_TWITTER_AUTH_EXISTS_SUCCESS';
export const GET_TWITTER_AUTH_EXISTS_FAIL = 'GET_TWITTER_AUTH_EXISTS_FAIL';