export const GET_NR_OF_ANALYSIS = "GET_NR_OF_ANALYSIS"
export const GET_NR_OF_ANALYSIS_SUCCESS = "GET_NR_OF_ANALYSIS_SUCCESS"
export const GET_NR_OF_ANALYSIS_FAIL = "GET_NR_OF_ANALYSIS_FAIL"

export const GET_ANALYSIS = "GET_ANALYSIS"
export const GET_ANALYSIS_SUCCESS = "GET_ANALYSIS_SUCCESS"
export const GET_ANALYSIS_FAIL = "GET_ANALYSIS_FAIL"